# Generated by Django 4.1.1 on 2022-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpredict',
            name='itching_skin',
            field=models.CharField(max_length=60),
        ),
    ]
